# url <- "https://row.githubusercontent.com/rafalab/dslabs/master/inst/extdata/murders.csv"
# dest_file<- "data/murders.csv"
# download.file(url, destfile = dest_file)

library(dslabs)
library(tidyverse)
murders<- murders
murders <- murders %>% mutate(region= factor(region), rate= population * 10^5)
save (murders, file="rda/murders.rda")


murders %>% mutate(abb= reorder(abb, rate))%>%
            ggplot(aes(abb, rate))+
            geom_bar(width=0.5, stat="identity", color="black")+
            coord_flip()

ggsave("figs/barplot.png")

########## In RStudio ########
# pick existing directory as new project
getwd()    # to confirm current working directory
save()    # save into .rda file, .RData is also fine but less preferred
ggsave("figs/barplot.png")    # save a plot generated by ggplot2 to a dir called "figs"